name: Devsecops Demo CI/CD
run-name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'  # Ignore changes to this file to prevent loops

jobs: 
  devsecops_pipeline:
   runs-on: ubuntu-latest
   steps:
    - name: Testing
      run: echo "Running tests..."